name: commit-lint

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  commit-lint:
    name: Validate conventional commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate PR title and commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .github/commitlint.config.mjs
          failOnWarnings: true
          helpURL: https://www.conventionalcommits.org/
